services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: quizapp
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: quizapp
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
    name: quizapp_pgdata